---
abstract: 'Perl class for image keyboard imagemap in Tags format creating.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-Keyboard-ImageMap-Tags
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  Encode: 0
  Error::Pure: 0.11
  HTML::Entities: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Image-Keyboard-ImageMap-Tags
  homepage: https://github.com/tupinek/Image-Keyboard-ImageMap-Tags
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Image-Keyboard-ImageMap-Tags
version: 0.01
